### ISSUE TITLE
"opt.development_extensions.wrap_url_and_doi" includes trailing dot in urls, leading to broken links.

### ISSUE THREAD

**Issue by dsifford** [Juris-M/citeproc-js#101]
Steps to reproduce:

1. Use style `american-medical-association`.
2. Enable `instance.engine.opt.development_extensions.wrap_url_and_doi = true`
3. Use this CSL:
    ```json
    {
        "type": "webpage",
        "title": "ALIEM - Academic Life in EM",
        "URL": "https://aliem.com",
        "container-title": "ALiEM",
        "accessed": {
            "raw": "2019/03/28"
        },
        "id": "3880912846"
    }
    ```
4. Observe the following HTML output:
    ```html
    <div class="csl-entry">
        <div class="csl-left-margin">1.</div>
        <div class="csl-right-inline">
            ALIEM - Academic Life in EM. ALiEM.
            <a href="https://aliem.com.">https://aliem.com.</a> Accessed March 28,
            2019.
        </div>
    </div>
    ```

This is particularly harmful also when the URL is a link to a file (e.g., ending in `.pdf`).

### Possibly related

https://github.com/dsifford/academic-bloggers-toolkit/issues/549

**Comment by fbennett** [comment]
Ouch, that's ugly. Fixed by https://github.com/Juris-M/citeproc-js/commit/f07c1cbb00f873ecec774e391776e5ca3a741a21, tagged as [1.1.228](https://github.com/Juris-M/citeproc-js/tree/1.1.228), released to `npm`.

Thanks for reporting this. A similar issue against DOIs was fixed last year, I missed that URLs were vulnerable to the same pattern.
