### ISSUE TITLE
`is-numeric` returning true unexpectedly

### ISSUE THREAD

**Issue by bwiernik** [Juris-M/citeproc-js#125]
I have the following variable:
```
[
  {"id":"Titlea","type":"report","version":"version: 2002, amended effective June 1, 2010, and January 1, 2017"}
]
```

It is testing `true` when given to `is-numeric`. I didn't think this should be the case considering that there are whole non-numeric words separated by whitespace.

**Comment by fbennett** [comment]
Yes, it looks like this should test false in the current CSL spec. In the early days of CSL, any string beginning with a number was treated as "numeric," and this behavior has probably just survived in subsequent processor revisions. I'll add a test and see what can be done.

**Comment by fbennett** [comment]
This will be simple to fix, it turns out, but a brief pause over the current state of affairs before committing. The reason this fails is that I've set off-spec behavior for the `is-numeric` test with `version` and `title` specifically. The special case of the test checks only whether the variable's value ends with a number. For `title` that makes sense, since the punctuation or locator label that immediately follows a title might vary, for clarity, if the title ends in a number. For `version` though, I can't see why that would be appropriate treatment. Let me think about it for a day. A first glance, though, I'm thinking that adding this to the processor's list of "numeric" variables, to apply the normal test (which returns `false` in this case) is a good fix - and would still pass every test to the CSL and CSL-M test suites. What do you think?

**Comment by bwiernik** [comment]
Off hand, I can’t think of a reason that would be appropriate behavior for `version` either. I’ll think about it too.

**Comment by fbennett** [comment]
I've gone ahead and made the release, tagged as 1.2.31.
