### ISSUE TITLE
"invalid language tag" error in 1.4.7

### ISSUE THREAD

**Issue by dstillman** [Juris-M/citeproc-js#142]
Resulting from the fix for https://github.com/Juris-M/citeproc-js/issues/138

Apparently `toLocaleLowerCase()`/`toLocaleUpperCase()` [will throw a `RangeError`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/toLocaleLowerCase#Exceptions) if an invalid locale is given, so it seems like there needs to be a try/catch with a fallback to `toLowerCase()`/`toUpperCase()`.

https://forums.zotero.org/discussion/84224/zotero-error-refreshing-report-id-337976002

**Comment by fbennett** [comment]
I encountered this bug when testing, and thought I'd dealt with it by
nornslizing the string. I'll add a try/catch then.

**Comment by fbennett** [comment]
Fixed in tag 1.4.11.

Can confirm that the bad language tags in the forum report pass without error in node.js v10. The [specification](https://tc39.es/ecma402/#sup-string.prototype.tolocaleuppercase) assumes valid tags, but doesn't say what should happen otherwise, so everyone come out looking good except us. :/ I've gathered the try/catch in a couple of functions, and adjusted the call everywhere. With luck this will serve a bit better.

**Comment by fbennett** [comment]
Looking at this again, the fallback could be made to `toLocaleUpperCase()` or `toLocaleLowerCase()`, without the array of locales, which would use the locale set in the environment. That *might* get things right in some failing cases. Or it might just cause additional confusion. I'll leave it on `toUpperCase()` and `toLowerCase()` for now.

**Comment by dstillman** [comment]
Yeah, I think without an explicit value it'd make sense to avoid all locale-based processing. Do we rely on the environment for anything else?

Zotero beta is out now with this fix. Thanks!

**Comment by fbennett** [comment]
There are some operations in the standalone module in `dateparser.js` that call bare `toLocaleLowerCase()`, but I don't think tha is used in Zotero. Everything else is tied to the locale array (field local [Jurism only], item locale, processor locale).
