### ISSUE TITLE
[Bug] - Newest CSL style added by the CSL team throws error due to "bibliography.tokens.length" being 0

### ISSUE THREAD

**Issue by dsifford** [Juris-M/citeproc-js#16]
Style in question: `Mercatus Center` https://github.com/citation-style-language/styles/blob/master/mercatus-center.csl

Here's where the issue happens (I have no idea what `tokens` is, so I can't really investigate much further)

![image](https://cloud.githubusercontent.com/assets/5240018/18116186/9d3326d0-6f13-11e6-9e90-c28c4c8d598a.png)

I've confirmed that the CSL XML is available to the `CSL.Engine` so that's not the issue.

**Comment by fbennett** [comment]
"tokens" is the list of functions that the processor walks through to produce the rendered form of a citation or bibliography entry. The style has no bibliography, so the length is zero. The expected behavior in that case is for `citeproc.makeBibliography()` to return `false`. Is that not happening?

**Comment by dsifford** [comment]
Nope, that's exactly what's happening.

My mistake. Didn't realize that was even an option!
