### ISSUE TITLE
HTML escaped in citeproc-js output when using citation marks

### ISSUE THREAD

**Issue by johanneswilm** [Juris-M/citeproc-js#46]
This seems to be similar to https://github.com/Juris-M/citeproc-js/issues/26 . When using this title:

    <span class="nocase">"PIAAC-Longitudinal (PIAAC-L) 2015"</span>
    
we get this output in AAA style:

    &#60;span class="nocase"&#62;"PIAAC-Longitudinal (PIAAC-L) 2015"&#60;/span&#62;.

(using citeproc 2.0.2 on npm)

**Comment by fbennett** [comment]
Hadn't anticipated this one. It's to do with an assumption the processor makes about straight quotes --- if they occur at the start of the string of have a leading space, they are recognized as openers, otherwise not. The lack of a space before the enclose quotation mark causes the recognition to fail, but the close quote is properly recognized. That triggers a nesting error on the "nocase" markup, so everything is passed through literal.

You might think that the quotes could just be dealt with by find-and-replace at the end of processing, but that won't work because we need to apply the nested quote characters specified in the style --- so the straight quotes are in effect not text characters, but a form of markup.

It will be a bit of a hack, but I think we can handle the use case without collateral breakage by spoofing in a space on the quote following the span, and then removing it (perhaps with some other adjustments) when the span is pulled out.

More soon.

**Comment by fbennett** [comment]
Arrived at [a patch](https://github.com/Juris-M/citeproc-js/commit/82730ccd44395ecd182b71436b5c0b1d3457ae7f), and pushed the new version to `npm`. Should fix the problem, let us know how it goes.

**Comment by johanneswilm** [comment]
Thanks! this works. What an odd issue!
