### ISSUE TITLE
#makeBibliography produces an empty bibliography after #previewCitationCluster

### ISSUE THREAD

**Issue by adomasven** [Juris-M/citeproc-js#51]
As part of https://github.com/zotero/zotero/pull/1242 we want to [insert citation previews](https://github.com/zotero/zotero/pull/1242/commits/3fddda4180030d9b9e08dd97296a0f0130ecbc66#diff-42b638bf8c4310962497ebd4d8edb53eR1550) without providing pre and post citations to the processor.

This works fine, however, after calling `previewCitationCluster()` like that, `CSLEngine.registry.reflist` is empty, even if `CSLEngine.registry.citationreg` is populated, which leads to `makeBibliography()` producing an empty bibl. I believe this [updateItems()](https://github.com/zotero/zotero/blob/2ab46d3697dcb4a6f2d813ab13b56a94ce19ddab/chrome/content/zotero/xpcom/citeproc.js#L5001) call is to blame.

**Comment by fbennett** [comment]
Glad to see this move! I'll get on it.

**Comment by fbennett** [comment]
I'll have some questions, but I'll start with some description from the `citeproc-js` side as context. I haven't been following the content of the changes under the zotero/zotero#1242  issue, so there may be some back-and-forth before I catch on. My first thought is that `previewCitationCluster()` probably isn't the thing to use here, but I need to listen up first.

`previewCitationCluster()` is a wrapper around `processCitationCluster()`, which is the bottleneck culprit that performs disambiguation and maintains citation state in the processor registry. It essentially runs the latter function, but invoking additional logic that reverses registry changes that would be caused by the insertion or edit, after the rendered sample text is produced. Invoked as intended (with pre- and post- arrays), it will take as long or a bit longer to return than a call to `processCitationCluster()`.

For a quick static representation of a cited item, I think `getCitationCluster()` will be more suitable. It doesn't touch the registry, and doesn't perform any heavyweight context evaluation. It's what `processCitationCluster()` calls once it's worked out what the correct parameters are for the elements of a citation. Since `getCitationCluster()` doesn't touch the registry, it won't add the static item to the bibliography. To do that in a lightweight way that avoids disambiguation, I think you could use `updateUncitedItems()`.

Does that roughly make sense, or am I misunderstanding how postponed rendering is meant to work?
