### ISSUE TITLE
[Bug] group as implicit conditional and choose conditional

### ISSUE THREAD

**Issue by tillheilmann** [Juris-M/citeproc-js#56]
group as implicit conditional and choose conditional do not always work together as expected. The MWE below produces output for, say, an entry type chapter with _no_ container-title when the variables called by a group (in this case: container-title) are empty.

    <?xml version="1.0" encoding="utf-8"?>
    <style xmlns="http://purl.org/net/xbiblio/csl" version="1.0" class="note" default-locale="de-DE" demote-non-dropping-particle="sort-only">
      <info>
        <title>Minimal working example (MWE)</title>
        <category citation-format="note"/>
        <id>http://www.tillheilmann.info/mwe</id>
        <link href="http://www.tillheilmann.info/" rel="documentation"/>
        <updated>2017-08-01T17:51:31+01:00</updated>
      </info>
      <macro name="X">
        <text variable="container-title"/>
      </macro>
      <macro name="Y">
        <choose>
          <if variable="container-title">
    	<text variable="container-title"/>
          </if>
        </choose>
      </macro>
      <citation>
        <layout>
          <group>
    	<text value="A"/>
    	<text variable="container-title"/>
          </group>
          <group>
          	<text value="B"/>
          	<choose>
          	  <if variable="container-title">
          	    <text variable="container-title"/>
          	  </if>
          	</choose>
          </group>
          <choose>
    	<if variable="container-title">
    	  <group>
    	    <text value="C"/>
    	    <text variable="container-title"/>
    	  </group>
    	</if>
          </choose>
          <group>
    	<text value="D"/>
    	<text macro="X"/>
          </group>
          <group>
    	<text value="E"/>
    	<text macro="Y"/>
          </group>
          <choose>
    	<if type="chapter">
    	  <group>
    	    <text value="F"/>
    	    <text macro="X"/>
    	  </group>
    	</if>
          </choose>
          <choose>
    	<if type="chapter">
    	  <group>
    	    <text value="G"/>
    	    <text macro="Y"/>
    	  </group>
    	</if>
          </choose>
        </layout>
      </citation>
    </style>

**Comment by fbennett** [comment]
This is expected behavior.

According to the [CSL specification](http://docs.citationstyles.org/en/1.0.1/specification.html#group), "`cs:group` implicitly acts as a conditional: `cs:group` and its child elements are suppressed if a) at least one rendering element in `cs:group` calls a variable (either directly or via a macro), and b) all variables that are called are empty."

Where a rendering element is masked by a condition that tests `false`, it is not called. Where no attempt is made to render a variable, (a) is not satisfied, so `cs:text` elements in the group that have a `value` attribute are rendered verbatim.
