### ISSUE TITLE
 _this._getCiteproc is not a function inside a web worker

### ISSUE THREAD

**Issue by dinkom** [Juris-M/citeproc-js#59]
I'm using Citeproc installed via yarn (version 2.1.181) and everything works fine in a usual use case. However, when I try creating a bibliography inside a web worker (to reduce the strain of the main thread), I get the following error when calling `processor.appendCitationCluster({ data })`:  `_this._getCiteproc is not a function`.

I caught the error inside a try catch block and even managed to call `processor.makeBibliography()` afterwards and it returned a correct array, but without any citation items inside.

This might not be due to Citeproc itself since it works outside web workers, but maybe you know where does the difference come from and how to make it work inside a web worker. Thanks!

**Comment by fbennett** [comment]
That function doesn't exist in the citeproc-js source, so I'm not sure what might be triggering the error. The `appendCitationCluster()` function should be considered deprecated (note-to-self: the docs should be checked on this). To prep for a call to `makeBibliography()`, it is enough to ship a keyed object of items to the worker, set up `sys.retrieveItem()` to pull IDs from it, and then invoke `updateItems()` in the worker to update the processor registry. The [ReadTheDocs docs](http://citeproc-js.readthedocs.io/en/latest/deployments.html) have a bibliography demo (broken until a few minutes ago, oops) that shows the sequence --- not a complete example for your purpose, since it doesn't use a worker, but it shows the pattern.

**Comment by dinkom** [comment]
@fbennett Thank you - you've helped more than you know :) 
I've inherited the code I'm working with so I supposed `_getCiteproc` is a citeproc-js method, but it was a custom method used in the override of `retrieveItem` and since the worker is in a separate file, it couldn't find the method. Anywho, fixed it and works just like it works outside the worker. Thanks again!
