### ISSUE TITLE
Bugs for Creators entered through Extra cheater syntax

### ISSUE THREAD

**Issue by bwiernik** [Juris-M/citeproc-js#6]
I've found some bugs with how citeproc-js seems to handle creator names entered using the Zotero Extra field and the cheater syntax.

If I enter a name like this:
{:editor: Book | Editor}

citeproc-js picks it up and recognizes that it is an editor, but three things don't work.

First, the "initialize-with" parameter for names isn't respected--["initialize-with"=". "] renders as:
(Book, Editor, Ed.) in apa.csl

Second, names entered via Extra don't seem to work correctly for <subsitute> parameters. For example, if a Report lacks an author, but has an editor in Extra, the citation renders as:
(1999). _Title_. Place: Publisher.

Interesting, what seems to be happening is that citeproc-js recognizes that there is an editor, but doesn't actually render the contexts. If I remove the editor from Extra, it renders as:
_Title_. (1999). Place: Publisher.

If there is both an editor and a translate in Extra (with the same name--so they should collapse), it renders as:
(1999). _Title_. (Translate, First, Trans.) Place: Publisher.

Third, collapsing of editor and translator doesn't work if one of the two names is defined through cheater syntax, but the other is not. (e.g., if Translator is entered into proper Zotero fields, but Editor is entered in Extra, they won't collapse into "Ed. & Trans.")--if both are in Extra, it works as expected.

**Comment by nickbart1980** [comment]
Just for clarification, for creators, what is the correct field separator between First and Last, `|` or `||`, and what is the correct syntax for *multiple* creators?

Both `{:editor: First|Last}` and `{:editor: First||Last}` in the Extra field are picked up, and (using chicago-author-date) rendered as “… Edited by Last, First. …”. 

(BTW, the output format that is expected here is “… Edited by First Last. …”; this does work as expected if a regular Editor field is used. This is possibly one more issue that should be added to @bwiernik’s list above.)

However, for *multiple* creators, neither `{:editor: First|Last}{:editor: FirstB|LastB}` nor any variant I tried rendered anything else but “… Edited by Last, First. …”.

**Comment by bwiernik** [comment]
You have to separate multiple creators by a newline.

**Comment by nickbart1980** [comment]
What’s the exact syntax? Could you give an example that works for you?

~~~
{:editor:First|Last
FirstB|LastB}
~~~

renders only one editor (though it's a combination of the two names):  “… Edited by LastB, First. …”.

**Comment by bwiernik** [comment]
Ah. It looks like multiple creators no longer works. It did in a previous release with this syntax:

{:editor: LastA | FirstA}
{:editor: LastB | FirstB}

**Comment by nickbart1980** [comment]
Aha, thanks, so I wasn't misremembering things. Hopefully this and the other issues listed above can be fixed at some point ...

**Comment by fbennett** [comment]
Took awhile for me to wake up on this, sorry. Documentation on the syntax is now [on ReadTheDocs](http://citeproc-js.readthedocs.io/en/latest/csl-json/markup.html#cheater-syntax-for-odd-fields), a fresh version of the processor is available as tag 1.1.132, and for Zotero users the [Propachi plugins](https://juris-m.github.io/downloads/#csl-stuff) have been updated. See how it goes.

**Comment by fbennett** [comment]
One update to fix some bugs, tag is now 1.1.133. [Propachi plugins](https://juris-m.github.io/downloads/#csl-stuff) also updated.

**Comment by bwiernik** [comment]
Working great! Really appreciate the fixes and the support for newline formatting vs. brace formatting.

**Comment by nickbart1980** [comment]
Runs nicely now, thanks. Just two thoughts:

(1) Date variables also seem to work well with date ranges (YYYY/YYYY, YYYY-MM/YYYY-MM, YYYY-MM-DD/YYYY-MM-DD) – maybe this fact could be added to the documentation?

(More advanced EDTF stuff [neg. years, circa, seasons] does not seem to be implemented yet, but once it is, the cheater fields will of course be great for testing since they permit sneaking dates past Zotero’s own somewhat problematic date parser. This of course presupposes that the parsing of the Extra field stays within citeproc-js’s remit.)

(2) I tend to think that overriding existing fields would be more useful. Using date ranges works great with the cheater syntax – but currently you have to leave Zotero’s own Date field empty for this to work. With overriding, there could be a date in Zotero’s Date field for sorting and display **and** a date range could be formatted correctly via the cheater syntax. – For another, different argument in favour of overriding (item type), see https://github.com/zotero/zotero/issues/846#issuecomment-165619931.

**Comment by fbennett** [comment]
@nickbart1980 On EDTF, now that Sylvester's library is out there, it should be possible to splice it into citeproc-js at some point. It would replace the processor's existing date parsing module, which is a hacked thing I wrote long ago just to keep things going. I don't have time to work on it now, but that seems to be the way forward on dates.

On overrides, that's a very good point. I'll add a processor option to select the behaviour, and make permit-override the default. That will be out shortly, I'll post when it's ready.

**Comment by fbennett** [comment]
@nickbart1980 Looking at overrides, limiting it on dates and types seems the way to go. For types, there is (almost) always a pre-existing value, so it pretty-much has to be permitted there. As you point out, the processor's date parsing engine may be slightly more capable than the calling application, so it makes sense there. For the others (names, ordinary variables), where an input field exists, it should be used; otherwise I do think there would be a risk of user confusion.

Code for testing coming up soon!

**Comment by fbennett** [comment]
Closing this, as I think the issues raised here were addressed quite awhile ago.
