### ISSUE TITLE
csl style error

### ISSUE THREAD

**Issue by mshd** [Juris-M/citeproc-js#85]
Using universite-laval-departement-des-sciences-historiques.csl I'm getting this error
`/home/admin/apps/martins/nodeparser/node_modules/citeproc/citeproc_commonjs.js:3997`
`blobs_start = state.fun.decorate[params[0]][params[1]].call(blob, state, blobs_start, params[2]);`
`TypeError: Cannot read property 'call' of undefined`

**Comment by fbennett** [comment]
Like #86, this processes normally in the test suite. The processor contains a lot of legacy code, and the likely cause of both issues is some incompatibility with the JS engine in Node. I can look into it, but I'll need details on the environment in order to reproduce the error:
1. What version of Node is throwing the error?
2. What code is used to instantiate the processor? (a minimal test framework if possible)
3. What is the exact input object that throws the error?
