### ISSUE TITLE
New output format

### ISSUE THREAD

**Issue by retorquere** [Juris-M/citeproc-js#9]
I add a new output format to the processor by adding it to CSL.Output.Formats, but I'm having an issue escaping URLs. From the looks of it, the URLs I produce through '@URL/true' are put through text_escape. Is there a way to prevent this? URLs need a non-standard escaping for markdown.

**Comment by fbennett** [comment]
Sorry for the loong delay in responding. There isn't currently a way to suspend application of escapes. It would tough to implement, since `text_escape` is applied to strings in the intermediate output "queue" object, after pointers to their origin are no longer available.

You've probably come up with a solution by now, but the only thing that comes to mind would be a hack that tacks a prefix onto that field, and logic in text_escape that strips the prefix without escaping when it is encountered.
